# Generated by Django 5.1.1 on 2024-09-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Veterinario')),
                ('telefono', models.CharField(max_length=100, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('dni', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
