# Generated by Django 5.1.2 on 2024-10-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_veterinario_delete_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='dni',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='DNI'),
        ),
    ]
