# Generated by Django 5.1.2 on 2024-10-21 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_veterinario_direccion_alter_veterinario_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido del Cliente')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(max_length=255, verbose_name='Direccion')),
                ('dni', models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Mascota')),
                ('especie', models.CharField(max_length=100, verbose_name='Especie')),
                ('raza', models.CharField(blank=True, max_length=100, null=True, verbose_name='Raza')),
                ('edad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('clientefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.cliente', verbose_name='Cliente')),
                ('veterinariofk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.veterinario', verbose_name='Veterinario')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del Turno')),
                ('hora', models.TimeField(verbose_name='Hora del  Turno')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo del Turno')),
                ('clientefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.cliente', verbose_name='Cliente')),
                ('mascotafk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.mascota', verbose_name='Mascota')),
                ('veterinariofk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.veterinario', verbose_name='Veterinario')),
            ],
        ),
    ]
